### ISSUE TITLE
jsfuck issue...

### ISSUE THREAD

**Issue by VeNoMouS** [PiotrDabkowski/Js2Py#155] opened 2019-04-01 04:16 UTC
```
>>> js2py.eval_js('(+(+!+[]+[+!+[]]+(!![]+[])[!+[]+!+[]+!+[]]+[!+[]+!+[]]+[+[]])+[])[+!+[]]')
u'1'
>>>
```

should translate to `.` instead it translated to `1`

**Comment by PiotrDabkowski** [comment] 2019-04-01 18:29
This boils down to the issue with string representation of numbers:
In js2py:
`1100000000000000000000 + ""  === "1100000000000000000000"`
In node:
`1100000000000000000000 + "" === "1.1e+21"`

This can be relatively easily fixed by changing the to string implementation:
https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/base.py#L605

**Comment by PiotrDabkowski** [comment] 2019-04-01 18:34
Also interestingly, http://www.jsfuck.com/ shows that it works on most of the characters, but for some of them it relies on builtin functions. For example for letter "C" it relies on the String.fontcolor which is not part of ECMA 5. You may need to use polyfills for these (yes you can simply import a polyfill in js2py).

**Comment by VeNoMouS** [comment] 2019-04-01 20:12
@pro-src what do you think?

**Comment by pro-src** [comment] 2019-04-01 22:11
> Also interestingly, http://www.jsfuck.com/ shows that it works on most of the characters, but for some of them it relies on builtin functions. For example for letter "C" it relies on the String.fontcolor which is not part of ECMA 5. You may need to use polyfills for these (yes you can simply import a polyfill in js2py).

Indeed. Cloudflare's definition for the letter C seems to be different:
```js
Function("return escape")()(("")["italics"]())[2]
```

They probably patched it to keep compatibility with es5.

**Comment by pro-src** [comment] 2019-04-03 10:42
I'll send a PR for this within the next couple of days if nobody has already started work on it.

**Comment by PiotrDabkowski** [comment] 2019-04-03 16:55
Thanks, I will not have time to work on it in the next week (enough coding at work...). The issue is due to the difference in Number.prototype.toString implementation between JS and Python. They are quite similar, but there are edge cases. Exact specification for JS documentation can be found here: https://www.ecma-international.org/ecma-262/5.1/#sec-9.8.1

**Comment by VeNoMouS** [comment] 2019-04-03 20:24
@PiotrDabkowski what about the py2 vs py3 ticket i raised as well? py3 just breaks with js2py..

**Comment by pro-src** [comment] 2019-04-05 23:22
I'm working on it.

`doubleToExponentialCString`: https://github.com/v8/v8/blob/9010424ff584c41d64a6589a7914f5bba1332db4/src/conversions.cc#L1115
`CreateExponentialRepresentation`: https://github.com/v8/v8/blob/9010424ff584c41d64a6589a7914f5bba1332db4/src/conversions.cc#L1083

tests: https://github.com/v8/v8/blob/master/test/webkit/number-toExponential.js

**Comment by pro-src** [comment] 2019-04-06 23:36
@PiotrDabkowski How can I call the internal NumberPrototype method `toExponential` from base.py? This might not be the best way to do it but to avoid code duplication. Advice welcome :)

Basically, I would insert the following into https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/base.py#L605
```py
# Min and max exponent value at which JS will return the number in scientific notation
if not (-7 < floor(log10(abs(self.value) < 21))):
   return  # call toExponential() on self.value
```

And use a modified version of the current toExponential function based on this gist: https://gist.github.com/pro-src/f70a8fae712fb603c6afc4e544611400

**Comment by PiotrDabkowski** [comment] 2019-04-07 00:07
@pro-src Thanks, I would avoid calling that, internal methods should not rely on methods from JS prototypes. 
Also, I am not sure if the end result would be exactly correct for **all** the the numbers. The easiest is to just implement this exactly: https://www.ecma-international.org/ecma-262/5.1/#sec-9.8.1 from scratch... If you have troubles let me know

**Comment by pro-src** [comment] 2019-04-07 00:16
@PiotrDabkowski Sure.

If I'm going to do that then I need to know how to get the digits as string.
The following doesn't give the expected output:
```py
'%.16f' % float('%e' % 11000010000000000000000) 
# '11000009999999999934464.0000000000000000'
# It's not clear how best to convert that into 1.100001e+21
```

**Comment by pro-src** [comment] 2019-04-07 00:30
@PiotrDabkowski the code is very small and efficient, it seems simplest to me and works. We don't have to kill two bird with one stone here, although that sounds preferable.

Lets just inline the code into base.py
```py
            elif not (-7 < floor(log10(abs(self.value))) < 21):
                # Remove the sign from negative zero
                x = 0 if self.value == 0 else self.value
                n = format(x, '-.%de' % 16).split('e')
                # Remove trailing zeros
                s = n[0].rstrip('.0') or '0'
                # Remove leading zeros from exponent
                e = int(n[1])

                return Js(unicode(s + ('e' if e < 0 else 'e+') + str(e)))
            elif isinstance(self.value,
                            long) or self.value.is_integer():  # dont print .0
                return Js(unicode(int(self.value)))
```

**Comment by pro-src** [comment] 2019-04-07 00:44
Regarding the spec: https://www.ecma-international.org/ecma-262/5.1/#sec-15.7.4.6
In a nut shell, the difference between to two sections is don't convert to scientific notation unless...
```py
if not (-7 < floor(log10(abs(self.value))) < 21):
    # convert it
```

**Comment by pro-src** [comment] 2019-04-07 00:59
@PiotrDabkowski If you need me to explain why this works, just lemme know. :wink:

**Comment by pro-src** [comment] 2019-04-07 05:17
I wrote a test generator and this definitely is not working for ***all*** numbers. So from scratch it is.

**Comment by pro-src** [comment] 2019-04-09 03:28
My tests seem to show that this issue has been over complicated.
If you convert the number to float before converting it to string then you automatically get the desired result. However, this does ***not*** work for `Number.prototype.toExponential` with converts any number to exponential notation with an arbitrary number of fraction digits.

```py
if self.value != 0 and not (-7 < floor(log10(abs(self.value))) < 21):
   s = Js(repr(float(self.value)))
```

For information, the following shows the exponent range in which python will automatically convert to scientific notation.
```py
if self.value != 0 and not (-4 < floor(log10(abs(self.value))) < 15):
   s = Js(repr(float(self.value)))
```

The python version may have a leading zero in the exponent which should be removed.

If you want to do this from scratch, I would prove the above method to not be working first which I've been unable to do. You'll want to get the digits as a string and for that I'd recommend reviewing this SO question: https://stackoverflow.com/questions/38847690/convert-float-to-string-without-scientific-notation-and-false-precision 

I'll update my PR soon.

**Comment by VeNoMouS** [comment] 2019-04-09 03:57
What about the `math.exp()` i showed you yesterday?

**Comment by pro-src** [comment] 2019-04-09 03:59
@VeNoMouS What about it?

**Comment by VeNoMouS** [comment] 2019-04-09 04:00
nm... i just tested an idea ignore that comment

**Comment by pro-src** [comment] 2019-04-09 04:05
@VeNoMouS If there is some useful application of `math.exp()` then I would recommend `math.expm1()` to get full precision instead of 11 places. If you think of something, let me know.

**Comment by pro-src** [comment] 2019-04-09 04:21
@PiotrDabkowski I'm signing off. I can adjust the PR if you'd like otherwise I'm leaving it to you.

**Comment by VeNoMouS** [comment] 2019-04-09 04:26
@pro-src get on discord more ;P

**Closed** 2019-04-16 20:33 UTC

**Comment by VeNoMouS** [comment] 2019-04-16 21:20
<3

**Comment by pro-src** [comment] 2019-04-20 20:55
https://github.com/PiotrDabkowski/Js2Py/commit/f6be867f1d1bd8b9f84d4de4812f91c123a227e5#r33251030
