### ISSUE TITLE
SyntaxError: invalid syntax for identifier named "not"

### ISSUE THREAD

**Issue by felixSchl** [PiotrDabkowski/Js2Py#44] opened 2016-05-27 11:48 UTC
Hey, I have been playing around with transpiling the compiled [neodoc](https://github.com/felixSchl/neodoc/) output to python. However when I run it, I get this SyntaxError:

```
>>> context.eval(js)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/js2py/evaljs.py", line 85, in eval
    self.execute(code)
  File "/usr/local/lib/python2.7/site-packages/js2py/evaljs.py", line 80, in execute
    exec(code, self._context)
  File "<string>", line 4, in <module>
  File "<string>", line 3, in PyJs_LONG_0_
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 827, in __call__
    return self.call(self.GlobalObject, args)
  File "/usr/local/lib/python2.7/site-packages/js2py/base.py", line 1267, in call
    return Js(self.code(*args))
  File "/usr/local/lib/python2.7/site-packages/js2py/host/jseval.py", line 42, in Eval
    executor(py_code)
  File "/usr/local/lib/python2.7/site-packages/js2py/host/jseval.py", line 49, in executor
    exec(code, globals())
  File "<string>", line 429
    def PyJs_anonymous_47_(PyJsArg_5f5f7375706572636c6173735f5072656c75646524646f74426f756e6465645f30_, conj, disj, not, this, arguments, var=var):
                                                                                                                      ^
SyntaxError: invalid syntax
>>>
```

I assume it has today with "not" being a python keyword? You can grab a copy of the source JS from here: https://registry.npmjs.org/neodoc/-/neodoc-0.3.0.tgz ("dist/docopt.purs.js").

**Comment by PiotrDabkowski** [comment] 2016-05-27 12:25
The problem is with `is_valid_py_name(name)` function. It checks whether name is a valid python name by compiling name+"+11". In python `not+11` is legal so it did not detect any problems with this name :) The solution is to check name+" = 11" instead. I have just pushed a fix.

**Closed by PiotrDabkowski** 2016-05-27 12:25 UTC

**Comment by felixSchl** [comment] 2016-05-27 12:26
Spot on 👍

**Comment by PiotrDabkowski** [comment] 2016-05-27 12:34
Also, I tried running it and it raises this exception:
`ReferenceError: process is not defined`

I know it is a built in object in Node.js but unfortunately it is not supported in Js2Py. If you want to use it you would have to implement similar object in python and add it to the JS context.

**Comment by felixSchl** [comment] 2016-05-27 12:37
Thanks for the pointer!

**Comment by PiotrDabkowski** [comment] 2016-05-27 15:25
After I am done with exams I will implement all node.js objects + maybe I will add JS 6 support. Afterwards maybe even DOM support using jsdom.js. sorry Js2Py did not work for you this time

**Comment by felixSchl** [comment] 2016-05-27 18:51
Dude this project is ace, no need to be apologetic. Is there any chance for a patch-level release to pypi that includes this fix?

**Comment by Lexcon** [comment] 2016-05-27 19:07
I agree. Totally ace.


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Felix Schlitter <notifications@github.com> 
Datum: 27-05-16  20:51  (GMT+01:00) 
Aan: PiotrDabkowski/Js2Py <Js2Py@noreply.github.com> 
Onderwerp: Re: [PiotrDabkowski/Js2Py] SyntaxError: invalid syntax for identifier
  named "not" (#44) 

Dude this project is ace, no need to be apologetic. Is there any chance for a patch-level release to pypi that includes this fix?

**Comment by PiotrDabkowski** [comment] 2016-05-27 20:28
Thanks, but it still needs 1 month of intensive work to make it as reliable as Node. Updated pip.

**Comment by felixSchl** [comment] 2016-05-27 20:36
Cheers! I've managed to convert neodoc to python and it's actually running! https://github.com/felixSchl/neodoc/tree/feature/python/tools. If you want to see it in action, you can clone the project, run `npm install && npm build && ./tools/to_python`. At the moment it runs very slow though. I wonder if that's because of the huge file or the code itself. Have not further diagnosed yet. I don't expect anyone would want to wait 3 seconds just for the CLI parser to come back.

**Comment by Lexcon** [comment] 2016-05-27 20:44
Would be interesting to cythonize the module and see what that does for 
speed. Maybe if I find time I'll run some performance tests somewhere 
next week.

I looked into your compilation/conversion code but didn't find myself 
qualified to start tweaking it or help bringing it up to JS6 compat level.

I think performance wise running the stuff doesn't need to be such an 
issue. I think it would not be typical to run entire applications using 
your tool, it's suitable for short snippets, where it doesn't matter 
that what should take 0.001 seconds actually takes 0.01 seconds.

Optimization wise I think scope setup and object wrapping are 
bottlenecks because they happen so often, since even 1 + 1 requires two 
times object wrapping and x + y requires double wrapping combined with 
double scope lookups.

Robert

**Comment by PiotrDabkowski** [comment] 2016-05-27 21:21
@felixSchl Js2Py is slow. This is both because JavaScript is much faster than python and because some overheads due to translation (about 5 times slower than manual translation). Also a suggestion - it is much easier to call functions JS functions. Just use .to_python method to convert them to python-like object: 

`run = docopt_purs.var.to_python().PS['Docopt.FFI'].run`

OR 
`run = docopt_purs.var.get(u'PS').get('Docopt.FFI').get('run').to_python()`

Both methods are equivalent. This makes things much easier, all the conversion from python to JS is done automatically and you can simply call run like normal python function:

```
run("Usage: foo bar", {
    'dontExit': True,
    'argv': [s for s in sys.argv[1:]],
    'env': {}})
```

@Lexcon Thanks, I will try to work on it after my exams - 3 weeks more. Cython is a very nice option. I think this whole translation is very problematic and interpreter would be much better solution.

**Comment by Lexcon** [comment] 2016-05-27 21:40
I'm not sure what you mean with translation versus interpreter? I think 
the way you set it up is excellent. I like the in-between step of having 
an AST like Esprima does it. Someone else could even write an in-between 
optimizer for the AST before emitting to python code. That's where Py3 
is evolving into now too: AST hooks.

Robert
